"""Initial schema

Revision ID: 44d41dbeff92
Revises: 
Create Date: 2026-07-05 12:11:36.416598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '44d41dbeff92'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('student', 'teacher', 'admin', name='roleenum'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('university', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('degree', sa.String(), nullable=True),
    sa.Column('field_of_study', sa.String(), nullable=True),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('advisor_links',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('student_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('teacher_email', sa.String(), nullable=False),
    sa.Column('teacher_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('theses',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('owner_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('advisor_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('field', sa.String(), nullable=True),
    sa.Column('degree_level', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'in_review', 'defended', 'archived', name='thesisstatusenum'), nullable=True),
    sa.Column('current_version_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['advisor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advisor_comments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('thesis_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('advisor_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tool_context', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'moderate', 'low', name='severityenum'), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['advisor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['thesis_id'], ['theses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('milestones',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('thesis_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'done', 'late', name='milestonestatusenum'), nullable=True),
    sa.Column('approved_by_advisor', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['thesis_id'], ['theses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thesis_versions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('thesis_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('file_ref', sa.String(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('diff_from_prev', sa.JSON(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['thesis_id'], ['theses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thesis_id', 'version_number')
    )
    op.create_table('analysis_snapshots',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('version_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tool_type', sa.String(), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['thesis_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chunks',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('version_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_label', sa.String(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['thesis_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('citation_records',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('version_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('citation_key', sa.String(), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('claim_location', sa.String(), nullable=True),
    sa.Column('exists_in_bib', sa.Boolean(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('format_ok', sa.Boolean(), nullable=True),
    sa.Column('supports_claim', sa.Enum('yes', 'no', 'partial', 'unverifiable', name='supportenum'), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_snippet', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['thesis_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flags',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('snapshot_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('type', sa.Enum('citation', 'plagiarism', 'novelty', 'quality', name='flagtypeenum'), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'moderate', 'low', name='severityenum'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('evidence_excerpt', sa.Text(), nullable=False),
    sa.Column('page_ref', sa.String(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['analysis_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('related_flag_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('batched', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['related_flag_id'], ['flags.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('flags')
    op.drop_table('citation_records')
    op.drop_table('chunks')
    op.drop_table('analysis_snapshots')
    op.drop_table('thesis_versions')
    op.drop_table('milestones')
    op.drop_table('advisor_comments')
    op.drop_table('theses')
    op.drop_table('advisor_links')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
