"""Add audit_logs and index foreign keys

Revision ID: 539706d7f27f
Revises: bf57e75b47bb
Create Date: 2026-07-09 23:21:41.672604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '539706d7f27f'
down_revision: Union[str, Sequence[str], None] = 'bf57e75b47bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('resource_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_snapshots_version_id'), 'analysis_snapshots', ['version_id'], unique=False)
    op.create_index(op.f('ix_chunks_version_id'), 'chunks', ['version_id'], unique=False)
    op.add_column('citation_records', sa.Column('reasoning', sa.Text(), nullable=True))
    op.create_index(op.f('ix_flags_snapshot_id'), 'flags', ['snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flags_snapshot_id'), table_name='flags')
    op.drop_column('citation_records', 'reasoning')
    op.drop_index(op.f('ix_chunks_version_id'), table_name='chunks')
    op.drop_index(op.f('ix_analysis_snapshots_version_id'), table_name='analysis_snapshots')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
