"""Add corpus_documents

Revision ID: 61c8925fa84c
Revises: 999af5ec4430
Create Date: 2026-07-09 14:16:34.552876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '61c8925fa84c'
down_revision: Union[str, Sequence[str], None] = '999af5ec4430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semanticscholar_searches',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('query_text', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_text')
    )
    op.create_table('corpus_documents',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source_type', sa.Enum('internal_thesis', 'external_paper', name='corpussourceenum'), nullable=False),
    sa.Column('source_thesis_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('indexed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_thesis_id'], ['theses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_corpus_embedding', 'corpus_documents', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_corpus_embedding', table_name='corpus_documents', postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('corpus_documents')
    op.drop_table('semanticscholar_searches')
    # ### end Alembic commands ###
