"""Add section_map

Revision ID: 999af5ec4430
Revises: 44d41dbeff92
Create Date: 2026-07-09 13:03:03.633174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '999af5ec4430'
down_revision: Union[str, Sequence[str], None] = '44d41dbeff92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thesis_versions', sa.Column('section_map', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thesis_versions', 'section_map')
    # ### end Alembic commands ###
