"""Add reviewer_sim_sessions

Revision ID: bf57e75b47bb
Revises: 61c8925fa84c
Create Date: 2026-07-09 22:31:23.758113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf57e75b47bb'
down_revision: Union[str, Sequence[str], None] = '61c8925fa84c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviewer_sim_sessions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('thesis_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('transcript', sa.JSON(), nullable=True),
    sa.Column('report', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['thesis_id'], ['theses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviewer_sim_sessions')
    # ### end Alembic commands ###
